// Objective-C API for talking to socketcluster-client/native Go package.
//   gobind -lang=objc -prefix=Go socketcluster-client/native
//
// File is generated by gobind. Do not edit.

#ifndef __GoSocketClusterClient_H__
#define __GoSocketClusterClient_H__

#include <Foundation/Foundation.h>

FOUNDATION_EXPORT void GoSocketClusterClientDisconnect();

FOUNDATION_EXPORT BOOL GoSocketClusterClientGetData(NSData** ret0_, NSError** error);

FOUNDATION_EXPORT BOOL GoSocketClusterClientNewSocketClusterClient(NSString* host, NSString* profileName, NSString* authToken, NSString* userAgent, BOOL secure, NSString* dbPath, NSError** error);

FOUNDATION_EXPORT BOOL GoSocketClusterClientSubscribe(NSData* data, NSString** ret0_, NSError** error);

FOUNDATION_EXPORT BOOL GoSocketClusterClientUnsubscribe(NSString* id, NSError** error);

#endif
